# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos-6.6"
  config.vm.hostname = "sfdlab"
  config.vm.provider "virtualbox"  
  config.vm.network :forwarded_port, guest: 4567, host: 45670, host_ip: "127.0.0.1"
  config.vm.synced_folder "/home/raul/Documentos", "/mnt"
  config.vm.provision "shell" do |s|
    s.path = "script.sh"
  end
end
