# -*- mode: ruby -*-
# vi: set ft=ruby :
boxes = [
{ :name => :web, :ip => "192.168.0.10", :ssh_port => '2201', :cpus => 1, :mem => 512},
{ :name => :db,  :ip => "192.168.0.11", :ssh_port => '2202', :cpus => 1,  :mem => 512},
]

VAGRANT_API_VERSION = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.box = "centos-6.6"
      config.vm.network "private_network", ip: opts[:ip]
      config.vm.network "forwarded_port", guest: 22, host: opts[:ssh_port]
      config.vm.hostname = "%s.vagrant" % opts[:name].to_s
      config.vm.synced_folder "~/Documentos", "/vagrant"
      config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", opts[:cpus]], if opts[:cpus]
        vb.customize ["modifyvm", :id, "--memory", opts[:mem]], if opts[:mem]
      end
    end
  end
end
end
end
